### ISSUE TITLE
Indexing issue caused by the plugin

### ISSUE THREAD

**Issue by bajrangprasad01** [Cybr0sis/Catdea#19] opened 2021-04-20 05:22 UTC
<img width="830" alt="Screenshot 2021-04-20 at 10 34 45 AM" src="https://user-images.githubusercontent.com/55761760/115341115-98da3a80-a1c5-11eb-9b16-5d11ff5728f2.png">

[Stactrace.log](https://github.com/Cybr0sis/Catdea/files/6340786/Stactrace.log)

[Included.log](https://github.com/Cybr0sis/Catdea/files/6340792/Included.log)

### About IntelliJ Version
IntelliJ IDEA 2021.1 (Ultimate Edition) Build #IU-211.6693.111, built on April 6, 2021 Runtime version: 11.0.10+9-b1341.35 x86_64 VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o. macOS 10.15.7 GC: ParNew, Non-Bundled Plugins: com.alayouni.ansiHighlight (1.2.4), com.intellij.ideolog (203.0.27.0), jms-messenger (1.5.0), com.github.setial (4.0.2), net.ashald.envfile (3.2.1), org.sonarlint.idea (4.14.2.28348), org.jetbrains.kotlin (211-1.4.32-release-IJ6693.72), com.cybrosis.catdea (1.1.6), ru.adelf.idea.dotenv (2021.1) Kotlin: 211-1.4.32-release-IJ6693.72

**Comment by Cybr0sis** [comment] 2021-06-03 07:32
Duplicate of #7

**Closed as completed by Cybr0sis** 2021-06-03 07:32 UTC
