### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by talasilar** [Cybr0sis/Catdea#5] opened 2019-06-24 02:26 UTC
indexed lengths={chars=5448, bytes=5561}
doc length=2487
file length=2535
cached PSI class com.intellij.psi.impl.source.PsiJavaFileImpl
PSI length=2487
projects with file: 1

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:180)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:150)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:118)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:72)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:147)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:89)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:68)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:290)

**Comment by Cybr0sis** [comment] 2019-07-05 12:00
Looks like duplicate of #6

**Closed by Cybr0sis** 2019-07-05 12:00 UTC
Labels: duplicate
